version: '3'

services:
  caddy:
    container_name: caddy
    image: caddy:2.8.4-alpine
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - caddy-config:/config
      - caddy-data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./html:/usr/share/caddy:ro

volumes:
  caddy-config:
  caddy-data:
