version: '3'

services:
  caddy:
    container_name: sudog-caddy
    image: caddy:2.8.4-alpine
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./certs:/root/certs:ro
    networks:
      - web
    depends_on:
      - flask

  flask:
    container_name: sudog-flask
    restart: unless-stopped
    build:
      context: app
    stop_signal: SIGINT
    networks:
      - web

networks:
  web:
    driver: bridge